#Indicamos la versión de la API
apiVersion: apps/v1
#Indicamos que este fichero es de un despliegue
kind: Deployment
#Metadatos del despliegue
metadata:
  name: elmeudesplegament
#Características del despliegue
spec:
  # Al inicio 3 réplicas (luego si queremos activamos autoescalado)
  replicas: 3
  #Selector de los pods
  selector:
    matchLabels:
      app: elmeudesplegament
  #Plantilla de los pods
  template:
    #Metadatos de los pods
    metadata:
      labels:
        app: elmeudesplegament
    #Caracteristicas de los pods
    spec:
      #Contenedor del pod
      containers:
      #Nombre, imagen y puerto expuesto
      - name: app-feta-kubernetes-flask
        image: alvarser/flaskperakubernetes
        ports:
        - containerPort: 5000
